name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B verify --file pom.xml
    - name: Docker login
      run: docker login ghcr.io -u drsylent -p ${{ github.token }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/drsylent/cloud-native-tutorial:demo
    - name: Push the Docker image
      run: docker push ghcr.io/drsylent/cloud-native-tutorial:demo
